#!/bin/sh
# Script to setup VM
set -e
# Update
export DEBIAN_FRONTEND=noninteractive
sudo apt-get update
# Web
sudo apt-get install -y nginx jq
sudo sed -i 's/80/1111/g' /etc/nginx/sites-enabled/default
sudo systemctl restart nginx
# Docker
curl -fsSL https://get.docker.com/ | sh
sudo usermod -aG docker devops
# Motd
sudo chmod -x /etc/update-motd.d/*
cat <<EOF >> /tmp/motd

---------------------------------------------------------
 docker run -dti --name challenge uknbr/devops-challenge
 docker exec -ti challenge sh
---------------------------------------------------------

Enjoy! =)

EOF
sudo cp -f /tmp/motd /etc/motd
# k8s
sudo wget -q https://github.com/rancher/k3d/releases/download/v4.2.0/k3d-linux-amd64 -O /usr/local/bin/k3d
sudo chmod +x /usr/local/bin/k3d
sudo wget -q "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" -O /usr/local/bin/kubectl
sudo chmod +x /usr/local/bin/kubectl
# End
exit 0